export const EN_STRINGS = {
  app_name: 'SYNAPSE',
  tap_hint: 'Tap to think',
  buy: 'Buy',
  sell: 'Sell',
  prestige: 'Awaken',
  discharge: 'Discharge',
  cascade: 'Cascade',
  insight: 'Insight',
  focus: 'Focus',
  consciousness: 'Consciousness',
  thoughts: 'Thoughts',
  memories: 'Memories',
  sparks: 'Sparks',
  per_second: '/s',
  charges: 'Charges',
  neurons_tab: 'Neurons',
  upgrades_tab: 'Upgrades',
  patterns_tab: 'Patterns',
  regions_tab: 'Regions',
  same_as_before: 'Same as before',
  start: 'Start',
  ad_unavailable: 'Ad not available',
  restore_purchases: 'Restore Purchases',
  settings: 'Settings',
  reduced_motion: 'Reduced motion',
  colorblind: 'Colorblind mode',
  hard_reset: 'Hard reset',
  hard_reset_confirm: 'Type RESET to confirm',
  feature_unlocked: 'New feature unlocked',
  awakening: 'Awakening',
  transcendence: 'Transcendence',
} as const;

export type StringKey = keyof typeof EN_STRINGS;
